apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service
        imagePullPolicy: IfNotPresent
        lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
        env:
            - name: POLAR_CATALOG_SERVICE_URI
              value: http://catalog-service            
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://polar-postgres/polardb_order
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://polar-postgres/polardb_order
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
        resources:
          limits:
            memory: "512Mi"
            cpu: "200m"
        ports:
        - containerPort: 9002
